config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'computers#index'
  get '/api_credentials', to: 'computers#credentials', as: 'api_credentials'
  get '/computers/:id/links', to: 'computers#link', as: 'computers_link'
  get '/computers/:id/policy', to: 'computers#policy', as: 'computers_policy'
end

app/models/api_credential.rb
class ApiCredential < ApplicationRecord
  validates_presence_of :api_name, :api_id, :api_key
  validates_uniqueness_of :api_name, :api_id, :api_key
end

app/models/api_result.rb
class ApiResult < ApplicationRecord
  validates_presence_of :result_count
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/computer.rb
class Computer < ApplicationRecord
  has_one :link
  has_one :policy

  validates_uniqueness_of :connector_guid
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :computer
end

app/models/policy.rb
class Policy < ApplicationRecord
  belongs_to :computer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, length: { minimum: 4 }
end

app/controllers/api_crendentials_controller.rb
class ApiCredentialsController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_computer, only: [:link, :policy]

  def index
    @computers = Computer.all
  end

  def credentials
    @credentials = ApiCredential.where(api_name: "5thcolumn").first
  end

  def link
    @link = @computer.link
  end

  def policy
    @policy = @computer.policy
  end

  private

  def set_computer
    @computer = Computer.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/computers/credentials.html.erb
<div class="container-fluid">
  <p>API ID: <%= @credentials.api_id %></p>
  <p>API KEY: <%= @credentials.api_key %></p>
</div>

app/views/computers/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">connector_guid</th>
      <th scope="col">hostname</th>
      <th scope="col">active/not-active</th>
      <th scope="col">connector_version</th>
      <th scope="col">operating_system</th>
      <th scope="col">external_ip</th>
      <th scope="col">group_guid</th>
      <th scope="col">install_date</th>
      <th scope="col">last_seen</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <th scope="row"><%= computer.id %></th>
        <td><%= computer.connector_guid %></td>
        <td><%= computer.hostname %></td>
        <% if computer.active %>
          <td>active</td>
        <% else %>
          <td>not-active</td>
        <% end %>
        <td><%= computer.connector_version %></td>
        <td><%= computer.operating_system %></td>
        <td><%= computer.external_ip %></td>
        <td><%= computer.group_guid %></td>
        <td><%= computer.install_date %></td>
        <td><%= computer.last_seen %></td>
        <td><%= link_to 'Link', computers_link_path(computer.id) %></td>
        <td><%= link_to 'Policy', computers_policy_path(computer.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/computers/link.html.erb
<div class="container-fluid">
  <h4>Links of <span class="text-success"><%= @link.computer.hostname %></span></h4>
  <p>COMPUTER: <span class="text-primary"><%= @link.computer_link %></span></p>
  <p>TRAJECTORY: <span class="text-primary"><%= @link.trajectory %></span></p>
  <p>GROUP: <span class="text-primary"><%= @link.group %></span></p>
</div>

app/views/computers/policy.html.erb
<div class="container-fluid">
  <h4>Policy of <span class="text-success"><%= @policy.computer.hostname %></span></h4>
  <p>GUID: <span class="text-primary"><%= @policy.guid %></span></p>
  <p>NAME: <span class="text-primary"><%= @policy.name %></span></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coding5thcolumn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand nav-link active" href="/">Coding5thcolumn</a>
      <form class="form-inline">
        <% if user_signed_in? %>
          <%= link_to 'Show Credentials', api_credentials_path, { class: "nav-link" } if current_user.admin? %>
          <%= link_to 'Sign Out', destroy_user_session_path, { class: "btn btn-outline-danger my-2 my-sm-0", method: :delete } %>
        <% else %>
          <%= link_to 'Sign In', new_user_session_path, { class: "btn btn-outline-success my-2 my-sm-0" } %>
        <% end %>
      </form>
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
</html>